
package com.epam.taskeleven.server.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "soapServiceService", targetNamespace = "http://www.epam.com/taskeleven/server/soap", wsdlLocation = "http://localhost:8180/LabTask11-server/NewsService/soapNewsService.wsdl")
public class SoapServiceService
    extends Service
{

    private final static URL SOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICESERVICE_EXCEPTION;
    private final static QName SOAPSERVICESERVICE_QNAME = new QName("http://www.epam.com/taskeleven/server/soap", "soapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8180/LabTask11-server/NewsService/soapNewsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICESERVICE_WSDL_LOCATION = url;
        SOAPSERVICESERVICE_EXCEPTION = e;
    }

    public SoapServiceService() {
        super(__getWsdlLocation(), SOAPSERVICESERVICE_QNAME);
    }

    public SoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICESERVICE_QNAME, features);
    }

    public SoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICESERVICE_QNAME);
    }

    public SoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICESERVICE_QNAME, features);
    }

    public SoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "soapServiceSoap11")
    public SoapService getSoapServiceSoap11() {
        return super.getPort(new QName("http://www.epam.com/taskeleven/server/soap", "soapServiceSoap11"), SoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "soapServiceSoap11")
    public SoapService getSoapServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epam.com/taskeleven/server/soap", "soapServiceSoap11"), SoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPSERVICESERVICE_EXCEPTION;
        }
        return SOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
